apiVersion: v1
kind: Service
metadata:
  name: vpromq01
spec:
  ports:
    - port: 15672
      targetPort: 15672  # Assuming vpromq01-port is the same as the targetPort
      protocol: TCP
  selector:
    app: vpromq01  # Assuming this matches the label of your deployment or pods
  type: ClusterIP
