apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 80
      targetPort: 8080  # Assuming vproapp-port is 8080 as per your Deployment
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer
